export enum RankMode {
  NORMAL = 'normal',
  RANK = 'rank',
  RANK_BALANCE = 'rank_balance',
}

export enum RankConfigStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  DELETED = 'deleted',
}

export enum RankSessionStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  DELETED = 'deleted',
  ENDED = 'ended',
}

export enum AutoGenerateDurationType {
  WEEK = 'week',
  MONTH = 'month',
}
