<script setup lang="ts">
import { ref, computed, useTemplateRef } from 'vue'
import { useI18n } from 'vue-i18n'
import { useForm } from '@tanstack/vue-form'
import { z } from 'zod'
import { toast } from '@/utils/toast'
import VButton from '@/components/ui/btn/v-button.vue'
import RankTierRewardEditor, {
  type TierRewardForm,
} from '@/components/rank/rank-tier-reward-editor.vue'
import { RankConfigStatus, RankMode, AutoGenerateDurationType } from '@/enums/rank.enum'
import { rankConfigService } from '@/services/api/rank-config.service'
import type { RankConfig, TierReward, TierRewardDto } from '@/interfaces/rank.interface'
import { ItemSource } from '@/enums/item.enum'
import { useZodForm } from '@/composables/useZodForm'

const emit = defineEmits<{ close: []; saved: [] }>()

const { t } = useI18n()
const dialogRef = useTemplateRef<HTMLDialogElement>('dialog')
const { fieldValidator } = useZodForm()

type Tab = 'basic' | 'daily' | 'session'
const activeTab = ref<Tab>('basic')
const currentItem = ref<RankConfig | null>(null)
const isEdit = computed(() => !!currentItem.value)

const rewardDaily = ref<TierRewardForm[]>([])
const rewardSession = ref<TierRewardForm[]>([])

const statusOptions = Object.values(RankConfigStatus).map((v) => ({
  value: v,
  label: t(`rankConfig.status.${v}`),
}))
const rankModeOptions = Object.values(RankMode).map((v) => ({
  value: v,
  label: t(`rankConfig.rankMode.${v}`),
}))
const durationTypeOptions = Object.values(AutoGenerateDurationType).map((v) => ({
  value: v,
  label: t(`rankConfig.autoGenerateDuration.${v}`),
}))

function parseTierRewards(rewards: TierReward[]): TierRewardForm[] {
  return (rewards ?? []).map((r) => ({
    tierId: typeof r.tier === 'string' ? r.tier : r.tier._id,
    currency: (r.reward?.currency ?? []).map((c) => ({ type: c.type, value: c.value })),
    items: (r.reward?.items ?? []).map((it) => ({
      itemId: typeof it.item === 'string' ? it.item : (it.item as any)._id,
      itemCode: typeof it.item === 'string' ? it.item : ((it.item as any).code ?? it.item),
      quantity: it.quantity,
      source: it.source || ItemSource.SYSTEM,
    })),
  }))
}

function toTierRewardDtos(forms: TierRewardForm[]): TierRewardDto[] {
  return forms
    .filter((f) => f.tierId)
    .map((f) => ({
      tier: f.tierId,
      reward: {
        currency: f.currency.filter((c) => c.value > 0),
        items: f.items.map((it) => ({
          item: it.itemId,
          quantity: it.quantity,
          rarity: '',
          source: it.source,
          metadata: {},
        })),
      },
    }))
}

const defaultFormValues = {
  code: '',
  rankMode: RankMode.RANK as RankMode,
  status: RankConfigStatus.ACTIVE as RankConfigStatus,
  initialPoint: 1000,
  winPoint: 30,
  losePoint: 20,
  autoGenerateEnable: false,
  autoGenerateDurationType: AutoGenerateDurationType.WEEK as AutoGenerateDurationType,
  autoGenerateDurationValue: 1,
}

const form = useForm({
  defaultValues: defaultFormValues,
  onSubmit: async ({ value }) => {
    const autoGenerate = {
      enable: value.autoGenerateEnable,
      ...(value.autoGenerateEnable && {
        duration: {
          type: value.autoGenerateDurationType,
          value: Number(value.autoGenerateDurationValue),
        },
      }),
    }
    const rewardDailyDto = toTierRewardDtos(rewardDaily.value)
    const rewardSessionDto = toTierRewardDtos(rewardSession.value)

    if (isEdit.value && currentItem.value) {
      await rankConfigService.update(currentItem.value._id, {
        status: value.status,
        ruleSet: {
          initialPoint: Number(value.initialPoint),
          winPoint: Number(value.winPoint),
          losePoint: Number(value.losePoint),
        },
        autoGenerate,
        rewardDaily: rewardDailyDto,
        rewardSession: rewardSessionDto,
      })
      toast.success(t('rankConfig.edit.success'))
    } else {
      await rankConfigService.create({
        code: value.code,
        rankMode: value.rankMode,
        status: value.status,
        ruleSet: {
          initialPoint: Number(value.initialPoint),
          winPoint: Number(value.winPoint),
          losePoint: Number(value.losePoint),
        },
        autoGenerate,
        rewardDaily: rewardDailyDto,
        rewardSession: rewardSessionDto,
      })
      toast.success(t('rankConfig.create.success'))
    }
    emit('saved')
    close()
  },
})

defineExpose({ open })

function open(item?: RankConfig) {
  currentItem.value = item ?? null
  activeTab.value = 'basic'
  if (item) {
    form.reset({
      code: item.code,
      rankMode: item.rankMode,
      status: item.status,
      initialPoint: item.ruleSet?.initialPoint ?? 1000,
      winPoint: item.ruleSet?.winPoint ?? 30,
      losePoint: item.ruleSet?.losePoint ?? 20,
      autoGenerateEnable: item.autoGenerate?.enable ?? false,
      autoGenerateDurationType: item.autoGenerate?.duration?.type ?? AutoGenerateDurationType.WEEK,
      autoGenerateDurationValue: item.autoGenerate?.duration?.value ?? 1,
    })
    rewardDaily.value = parseTierRewards(item.rewardDaily)
    rewardSession.value = parseTierRewards(item.rewardSession)
  } else {
    form.reset(defaultFormValues)
    rewardDaily.value = []
    rewardSession.value = []
  }
  dialogRef.value?.showModal()
}

function close() {
  emit('close')
  dialogRef.value?.close()
}
</script>

<template>
  <dialog ref="dialog" class="modal">
    <div class="modal-box max-w-xl">
      <div class="absolute top-3 right-3">
        <VButton type="button" class="btn-ghost btn-circle" @click="close"> ✕ </VButton>
      </div>
      <h3 class="mb-3 text-lg font-semibold">
        {{ isEdit ? t('rankConfig.edit.title') : t('rankConfig.create.title') }}
      </h3>

      <form @submit.prevent="form.handleSubmit">
        <!-- Tabs -->
        <div role="tablist" class="tabs tabs-border mb-3">
          <button
            type="button"
            role="tab"
            class="tab"
            :class="{ 'tab-active': activeTab === 'basic' }"
            @click="activeTab = 'basic'"
          >
            {{ t('rankConfig.rewards.tabBasic') }}
          </button>
          <button
            type="button"
            role="tab"
            class="tab"
            :class="{ 'tab-active': activeTab === 'daily' }"
            @click="activeTab = 'daily'"
          >
            {{ t('rankConfig.rewards.rewardDaily') }}
            <span v-if="rewardDaily.length" class="badge badge-sm ml-1.5">{{
              rewardDaily.length
            }}</span>
          </button>
          <button
            type="button"
            role="tab"
            class="tab"
            :class="{ 'tab-active': activeTab === 'session' }"
            @click="activeTab = 'session'"
          >
            {{ t('rankConfig.rewards.rewardSession') }}
            <span v-if="rewardSession.length" class="badge badge-sm ml-1.5">{{
              rewardSession.length
            }}</span>
          </button>
        </div>

        <div class="-mx-6 max-h-[60dvh] overflow-y-auto px-6">
          <!-- Tab: basic -->
          <div v-show="activeTab === 'basic'" class="flex flex-col gap-4">
            <div class="grid grid-cols-2 gap-3">
              <form.Field name="code" :validators="{ onChange: fieldValidator(z.string().min(1)) }">
                <template #default="{ field }">
                  <fieldset class="fieldset">
                    <legend class="fieldset-legend">{{ t('rankConfig.fields.code') }}</legend>
                    <input
                      :value="field.state.value"
                      :disabled="isEdit"
                      type="text"
                      class="input input-bordered w-full font-mono"
                      :placeholder="t('rankConfig.fields.code')"
                      @input="field.handleChange(($event.target as HTMLInputElement).value)"
                      @blur="field.handleBlur()"
                    />
                    <p v-if="field.state.meta.errors[0]" class="text-error mt-1 text-xs">
                      {{ field.state.meta.errors[0] }}
                    </p>
                  </fieldset>
                </template>
              </form.Field>

              <form.Field name="rankMode">
                <template #default="{ field }">
                  <fieldset class="fieldset">
                    <legend class="fieldset-legend">{{ t('rankConfig.fields.rankMode') }}</legend>
                    <select
                      :value="field.state.value"
                      :disabled="isEdit"
                      class="select select-bordered w-full"
                      @change="
                        field.handleChange(($event.target as HTMLSelectElement).value as RankMode)
                      "
                    >
                      <option v-for="opt in rankModeOptions" :key="opt.value" :value="opt.value">
                        {{ opt.label }}
                      </option>
                    </select>
                  </fieldset>
                </template>
              </form.Field>
            </div>

            <form.Field name="status">
              <template #default="{ field }">
                <fieldset class="fieldset">
                  <legend class="fieldset-legend">{{ t('rankConfig.fields.status') }}</legend>
                  <select
                    :value="field.state.value"
                    class="select select-bordered w-full"
                    @change="
                      field.handleChange(
                        ($event.target as HTMLSelectElement).value as RankConfigStatus
                      )
                    "
                  >
                    <option v-for="opt in statusOptions" :key="opt.value" :value="opt.value">
                      {{ opt.label }}
                    </option>
                  </select>
                </fieldset>
              </template>
            </form.Field>

            <div class="rounded-box bg-base-200 p-3">
              <p class="mb-2 text-sm font-medium">Rule Set</p>
              <div class="grid grid-cols-3 gap-3">
                <form.Field
                  name="initialPoint"
                  :validators="{ onChange: fieldValidator(z.number().min(0)) }"
                >
                  <template #default="{ field }">
                    <fieldset class="fieldset">
                      <legend class="fieldset-legend">
                        {{ t('rankConfig.fields.initialPoint') }}
                      </legend>
                      <input
                        :value="field.state.value"
                        type="number"
                        class="input input-bordered w-full"
                        @input="field.handleChange(+($event.target as HTMLInputElement).value)"
                        @blur="field.handleBlur()"
                      />
                      <p v-if="field.state.meta.errors[0]" class="text-error mt-1 text-xs">
                        {{ field.state.meta.errors[0] }}
                      </p>
                    </fieldset>
                  </template>
                </form.Field>
                <form.Field
                  name="winPoint"
                  :validators="{ onChange: fieldValidator(z.number().min(0)) }"
                >
                  <template #default="{ field }">
                    <fieldset class="fieldset">
                      <legend class="fieldset-legend">{{ t('rankConfig.fields.winPoint') }}</legend>
                      <input
                        :value="field.state.value"
                        type="number"
                        class="input input-bordered w-full"
                        @input="field.handleChange(+($event.target as HTMLInputElement).value)"
                        @blur="field.handleBlur()"
                      />
                      <p v-if="field.state.meta.errors[0]" class="text-error mt-1 text-xs">
                        {{ field.state.meta.errors[0] }}
                      </p>
                    </fieldset>
                  </template>
                </form.Field>
                <form.Field
                  name="losePoint"
                  :validators="{ onChange: fieldValidator(z.number().min(0)) }"
                >
                  <template #default="{ field }">
                    <fieldset class="fieldset">
                      <legend class="fieldset-legend">
                        {{ t('rankConfig.fields.losePoint') }}
                      </legend>
                      <input
                        :value="field.state.value"
                        type="number"
                        class="input input-bordered w-full"
                        @input="field.handleChange(+($event.target as HTMLInputElement).value)"
                        @blur="field.handleBlur()"
                      />
                      <p v-if="field.state.meta.errors[0]" class="text-error mt-1 text-xs">
                        {{ field.state.meta.errors[0] }}
                      </p>
                    </fieldset>
                  </template>
                </form.Field>
              </div>
            </div>

            <div class="rounded-box bg-base-200 p-3">
              <form.Field name="autoGenerateEnable">
                <template #default="{ field }">
                  <div class="flex items-center gap-2">
                    <input
                      :id="`auto-gen-${isEdit ? 'edit' : 'create'}`"
                      :checked="field.state.value"
                      type="checkbox"
                      class="checkbox checkbox-sm"
                      @change="field.handleChange(($event.target as HTMLInputElement).checked)"
                    />
                    <label
                      :for="`auto-gen-${isEdit ? 'edit' : 'create'}`"
                      class="cursor-pointer text-sm font-medium"
                    >
                      {{ t('rankConfig.fields.autoGenerate') }}
                    </label>
                  </div>
                </template>
              </form.Field>

              <form.Subscribe :selector="(s) => s.values.autoGenerateEnable">
                <template #default="enabled">
                  <div v-if="enabled" class="mt-3 grid grid-cols-2 gap-3">
                    <form.Field name="autoGenerateDurationType">
                      <template #default="{ field }">
                        <fieldset class="fieldset">
                          <legend class="fieldset-legend">
                            {{ t('rankConfig.fields.autoGenerateDurationType') }}
                          </legend>
                          <select
                            :value="field.state.value"
                            class="select select-bordered w-full"
                            @change="
                              field.handleChange(
                                ($event.target as HTMLSelectElement)
                                  .value as AutoGenerateDurationType
                              )
                            "
                          >
                            <option
                              v-for="opt in durationTypeOptions"
                              :key="opt.value"
                              :value="opt.value"
                            >
                              {{ opt.label }}
                            </option>
                          </select>
                        </fieldset>
                      </template>
                    </form.Field>
                    <form.Field
                      name="autoGenerateDurationValue"
                      :validators="{ onChange: fieldValidator(z.number().min(1)) }"
                    >
                      <template #default="{ field }">
                        <fieldset class="fieldset">
                          <legend class="fieldset-legend">
                            {{ t('rankConfig.fields.autoGenerateDurationValue') }}
                          </legend>
                          <input
                            :value="field.state.value"
                            type="number"
                            min="1"
                            class="input input-bordered w-full"
                            @input="field.handleChange(+($event.target as HTMLInputElement).value)"
                            @blur="field.handleBlur()"
                          />
                          <p v-if="field.state.meta.errors[0]" class="text-error mt-1 text-xs">
                            {{ field.state.meta.errors[0] }}
                          </p>
                        </fieldset>
                      </template>
                    </form.Field>
                  </div>
                </template>
              </form.Subscribe>
            </div>
          </div>

          <!-- Tab: rewardDaily -->
          <div v-show="activeTab === 'daily'">
            <RankTierRewardEditor v-model="rewardDaily" />
          </div>

          <!-- Tab: rewardSession -->
          <div v-show="activeTab === 'session'">
            <RankTierRewardEditor v-model="rewardSession" />
          </div>
        </div>

        <div class="modal-action">
          <VButton type="button" class="btn-ghost" @click="close">{{ t('common.cancel') }}</VButton>
          <VButton type="submit" class="btn-primary" :loading="form.state.isSubmitting">
            {{ t('common.save') }}
          </VButton>
        </div>
      </form>
    </div>
  </dialog>
</template>
