import type { BaseResource } from '@/interfaces/base-resource.interface'
import type { PaginationFilter } from '@/interfaces/pagination.interface'
import type {
  RankMode,
  RankConfigStatus,
  RankSessionStatus,
  AutoGenerateDurationType,
} from '@/enums/rank.enum'

export interface RuleSet {
  initialPoint: number
  winPoint: number
  losePoint: number
}

export interface AutoGenerateDuration {
  type: AutoGenerateDurationType
  value: number
}

export interface AutoGenerate {
  enable: boolean
  duration?: AutoGenerateDuration
}

export interface CurrencyReward {
  type: string
  value: number
}

export interface ItemReward {
  item: string | { _id: string; code: string }
  quantity: number
  rarity: string
  source: string
  metadata: Record<string, unknown>
}

export interface MailRewards {
  currency: CurrencyReward[]
  items: ItemReward[]
}

export interface TierReward {
  tier: string | { _id: string; code: string }
  reward: MailRewards
}

export interface RankConfig extends BaseResource {
  code: string
  rankMode: RankMode
  status: RankConfigStatus
  ruleSet: RuleSet
  rewardDaily: TierReward[]
  rewardSession: TierReward[]
  autoGenerate: AutoGenerate
}

export interface RankConfigFilter extends PaginationFilter {
  status?: RankConfigStatus
  rankMode?: RankMode
}

export interface TierRewardDto {
  tier: string
  reward: {
    currency: CurrencyReward[]
    items: { item: string; quantity: number; rarity: string; source: string; metadata: Record<string, unknown> }[]
  }
}

export interface CreateRankConfigDto {
  code: string
  rankMode: RankMode
  status?: RankConfigStatus
  ruleSet: RuleSet
  rewardDaily?: TierRewardDto[]
  rewardSession?: TierRewardDto[]
  autoGenerate?: AutoGenerate
}

export interface UpdateRankConfigDto {
  status?: RankConfigStatus
  ruleSet?: RuleSet
  rewardDaily?: TierRewardDto[]
  rewardSession?: TierRewardDto[]
  autoGenerate?: AutoGenerate
}

export interface CloneRankConfigDto {
  code: string
  rankMode: RankMode
}

export interface RankSession extends BaseResource {
  rankConfigId: string
  code: string
  rankMode: RankMode
  ruleSet: RuleSet
  rewardDaily: TierReward[]
  rewardSession: TierReward[]
  status: RankSessionStatus
  session: number
  startDate: string
  endDate: string
}

export interface RankSessionFilter extends PaginationFilter {
  status?: RankSessionStatus
  rankMode?: RankMode
  rankConfigId?: string
}

export interface CreateRankSessionDto {
  rankConfigId: string
  startDate: string
  endDate: string
  status?: RankSessionStatus
}

export interface UpdateRankSessionDto {
  status?: RankSessionStatus
  startDate?: string
  endDate?: string
  rewardDaily?: TierRewardDto[]
  rewardSession?: TierRewardDto[]
  applyToConfig?: boolean
}

export interface RankTierConfig extends BaseResource {
  code: string
  minPoint: number
}

export type RankTierConfigFilter = PaginationFilter

export interface CreateRankTierConfigDto {
  code: string
  minPoint: number
}

export interface UpdateRankTierConfigDto {
  code?: string
  minPoint?: number
}

export interface RankHallOfFame extends BaseResource {
  rankSession: string | RankSession
  rank1: string | null
  rank2: string | null
  rank3: string | null
}

export type RankHallOfFameFilter = PaginationFilter
